name: Build and Deploy Next.js 15+ Static Site to Azure Web App - peoplesgroup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js static site
        run: npm run build
        # This automatically generates the static `out/` folder with output: 'export' in next.config.js

      - name: Upload out folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-out
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for Azure login
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-out

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DBACFFEDD35346BD90EEB50EB07C8C72 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1FAB7780F6BE468C99AC9BF18ACF8B2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4306FA90B7246BDB6C96C7C4E66844D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'peoplesgroup'
          slot-name: 'Production'
          package: ./out
